uclibs/staff-directory-23

app/controllers/employees_controller.rb, app/views/employees/_employee.json.jbuilder, app/views/employees/_employees.html.erb, spec/controllers/employees_controller_spec.rb
Updated controllers and other to correct sorting by default and by department
=> updated files for correct sorting

scripts/start_qp.sh
Had to remove a few instances of "aaec" left in this file to insure puma restarts
=> corrected deploy script

app/controllers/employees_controller.rb
=> remove line in controller

.circleci/config.yml, Gemfile, Gemfile.lock
When doing rails server locally, could not find the correct mysql version, as it was pinned previously. Unpinning the version worked. 
There are two commits as I forgot to run bundle update, so the first commit did not have correct mysql code.
=> Unpinmysql

app/views/layouts/application.html.erb, tmp/puma/.keep
This fixes the webpacker message and the puma message on rail server
=> Removes unnecessary call to missing application.js and creates puma folder.

app/views/layouts/application.html.erb, config/deploy/qa.rb
This should fix the logout issue. Code changes:
<% if user_signed_in? %>
<p> <i>You are signed in.</i> </p>
<%# link_to "Logout", destroy_user_session_path, method: :delete %>
**<%= button_to 'Logout', destroy_user_session_path, method: :delete %>**
<% else %> 
<p class="signin"> <%= link_to "Login", new_user_session_path %></p>
<% end %>
=> replace logout with button to fix logout issue

.coveralls.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
Per issue #116 I added code to app for coveralls. Updated file that was not explicitly calling coveralls.
=> Coveralls setup

README.md
Fixes:#140
This PR adds instructions for how to set up and run the app in the local environment and removes the brakeman report.
=> 140 - Add local start instructions

package.json, yarn.lock
package.json and yarn.lock updated.
=> update webpack server version to 4

scripts/start_qp.sh
-update start script for:
1. removing line break 
2. change .env.production to .env.production.local
=> update start script

scripts/start_qp.sh
=> update start script (#168)

config/environments/production.rb
change value of  config.action_mailer.default_url_options 
config.action_mailer.default_url_options = { host: ENV['STADIR_PRODUCTION_MAILER_URL'] }
was this:
=> Fix productionfile

config/environments/production.rb
Correct this line:
config.public_file_server.enabled = true
=> corrects public server line in production.rb

app/assets/stylesheets/application.css, app/views/layouts/application.html.erb
update code in application, below footer partial: changed button_to to link_to to prevent javascript from trying to submit, causing the error. 
Updated styles for link_to to look like a button. :-)
=> modified to fix #178

yarn.lock
Ran `yarn upgrade` in preparation for upgrade to Rails 7.
=> LIBSTAFDIR-19 Run yarn upgrade in prep for upgrade to Rails 7

yarn.lock
Reverts uclibs/staff-directory-23#207
=> Revert "Run yarn upgrade in prep for upgrade to Rails 7"

yarn.lock
Reverts uclibs/staff-directory-23#205
=> Revert "Bump express from 4.19.2 to 4.21.0"

yarn.lock
Reverts uclibs/staff-directory-23#202
=> Revert "LIBSTAFDIR-19 Run yarn upgrade in prep for upgrade to Rails 7"

Gemfile.lock, config/webpack/environment.js, package.json, yarn.lock
**### excuse my typo in the branch name.** 
This updated webpack since many of the security issues were related to webpack updates.
=> Do first: Updated webpack

.bundler-audit.yml, Gemfile, Gemfile.lock
=> pin nokogiri , etc
